name: Docker

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update scripts permissions
        run: chmod 0755 .github/scripts/*.sh

      - name: Build image
        if: ${{ startsWith(github.ref, 'refs/heads/') }}
        run: .github/scripts/build-image.sh

      - name: Login to GitHub Container Registry
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push image
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: .github/scripts/build-image.sh
        env:
          DEPLOY: 1
